Repository gtt-project/redmine_gtt, pull requests merged in 2022-07, with the labels that each got.

#156 Ftr/api map config
  README.md
  app/controllers/gtt_configuration_controller.rb
  app/views/projects/show.api.rsb
  config/routes.rb
  doc/api.md
  init.rb
Labels: enhancement

#160 Updated README.md - Authors section
  README.md
Labels: documentation

#162 Flatten geojson coordinates before array length comparison
  init.rb
  lib/redmine_gtt/patches/issue_patch.rb
  test/unit/issue_test.rb
Labels: bug
